// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chessboard: typeof import('./components/Chessboard.vue')['default']
    ChessboardPiece: typeof import('./components/ChessboardPiece.vue')['default']
    ChessboardSquare: typeof import('./components/ChessboardSquare.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
